branches:
  except:
    - /^v?([0-9.]+)+[^.]\+sha\.[0-9a-f]{5,40}$/

install:
- git submodule update --init
- pip install --user --upgrade pip
- pip install --user plumbum

build_script:
- python -u appveyor.py

after_build:
- ps: mv OpenBLASConfig.cmake opt/
- ps: |
    7z a -ttar windows.tar -r ./opt/*
    7z a -tgzip windows.tar.gz windows.tar

artifacts:
- path: windows.tar.gz
  type: file
  name: windows

deploy:
- artifact: windows
  release: $(git --git-dir=./OpenBLAS/.git describe)+sha.$(git rev-parse --short HEAD)
  provider: GitHub
  force_update: true
  auth_token:
    branch: master
    secure: "31lCn0ra+kS6jDupOSkXxiGpzZ1slUrJ2IUiyBuwzBkJ1aX9GdpEu3ycmdyCRJ09"