environment:
  API_KEY:
    secure: G6Uxcu68rmW9z3Z9xU5j5N7ZtxFFR7KazDGGLf4BNbrrOvvn/LNFOCtGWWjyh4k9

branches:
  except:
    - /^v?([0-9.]+)+[^.]\+sha\.[0-9a-f]{5,40}$/

install:
- git submodule update --init
- python -m pip install --user --upgrade pip
- pip install --user plumbum

build_script:
- python -u appveyor.py

after_build:
- ps: $env:release_name="$(git --git-dir=./OpenBLAS/.git describe)+sha.$(git rev-parse --short HEAD)"
- ps: mv OpenBLASConfig.cmake opt/
- ps: |
    7z a -ttar windows.tar -r ./opt/*
    7z a -tgzip windows.tar.gz windows.tar

artifacts:
- path: windows.tar.gz
  type: file
  name: windows

deploy:
- artifact: windows
  release: $(release_name)
  provider: GitHub
  force_update: true
  auth_token:
    branch: master
    secure: G6Uxcu68rmW9z3Z9xU5j5N7ZtxFFR7KazDGGLf4BNbrrOvvn/LNFOCtGWWjyh4k9

after_deploy:
  - ps: |
      cd test
      cmake -DOpenBLAS_github_authtoken=$Env:API_KEY .
      cmake --build . --target bootstrap-test
      ./bootstrap-test
