
install:
- git submodule update --init
- pip install --user --upgrade pip
- pip install --user plumbum

build_script:
- python -u appveyor.py

after_build:
- ps: mv OpenBLASConfig.cmake opt/
- ps: |
    7z a -ttar windows.tar -r ./opt/*
    7z a -tgzip windows.tar.gz windows.tar

artifacts:
- path: windows.tar.gz
  type: file
  name: windows

deploy:
- prerelease: false
  artifact: windows
  provider: GitHub
  force_update: true
  auth_token:
    secure: "31lCn0ra+kS6jDupOSkXxiGpzZ1slUrJ2IUiyBuwzBkJ1aX9GdpEu3ycmdyCRJ09"
  draft: false
  on:
    appveyor_repo_tag: true

- prerelease: true
  artifact: windows
  provider: GitHub
  release: latest
  force_update: true
  auth_token:
    secure: "31lCn0ra+kS6jDupOSkXxiGpzZ1slUrJ2IUiyBuwzBkJ1aX9GdpEu3ycmdyCRJ09"
  draft: false
  on:
    branch: master
    appveyor_repo_tag: false